# Generated by Django 4.0.3 on 2022-03-13 19:31

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=core.helpers.RandomFileName('categories-icons')),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.helpers.RandomFileName('suppliers')),
        ),
    ]
