# Generated by Django 4.0.3 on 2022-03-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_category_background_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filters_fields',
        ),
    ]
