# Generated by Django 4.0.3 on 2022-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_remove_category_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='categories-icons'),
        ),
    ]
