# Generated by Django 4.0.3 on 2022-03-13 22:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=core.helpers.RandomFileName('categories-icons')),
        ),
    ]
