# Generated by Django 4.0.3 on 2022-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_rename_category_id_supplier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('caterer', 'caterer'), ('reception', 'reception'), ('other', 'other')], max_length=200),
        ),
    ]
