# Generated by Django 4.0.3 on 2022-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_tag_name_en_tag_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier',
            field=models.ManyToManyField(to='suppliers.tag'),
        ),
        migrations.DeleteModel(
            name='SupplierTag',
        ),
    ]
