# Generated by Django 4.0.3 on 2022-03-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_supplier_supplier_delete_suppliertag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier',
            new_name='tag',
        ),
    ]
