# Generated by Django 4.0.3 on 2022-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_alter_supplier_price_range_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_range',
            field=models.IntegerField(blank=True, choices=[(1, '€'), (2, '€€'), (3, '€€€')], max_length=200),
        ),
    ]
