# Generated by Django 4.0.2 on 2022-02-19 20:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('background', models.CharField(blank=True, max_length=200)),
                ('filters_fields', models.TextField(blank=True, default='')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='providers.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('price_range', models.CharField(blank=True, max_length=200)),
                ('adress', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('caterer_free', models.BooleanField()),
                ('brewer_free', models.BooleanField()),
                ('furnitures_included', models.BooleanField()),
                ('dishes_included', models.BooleanField()),
                ('gite_included', models.BooleanField()),
                ('corkage_fee', models.BooleanField()),
                ('buffet', models.BooleanField()),
                ('echoppes', models.BooleanField()),
                ('menu', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.category')),
            ],
        ),
    ]
