# Generated by Django 4.0.2 on 2022-02-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_category_background_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background',
            field=models.ImageField(blank=True, upload_to='categories/background'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='categories/icons'),
        ),
    ]
