# Generated by Django 4.0.2 on 2022-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_category_background_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
