# Generated by Django 4.0.2 on 2022-03-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_category_description_en_category_description_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
